### PR TITLE
Added extend_expiry method to the Server model

### PR DESCRIPTION
**Pull request by rubiojr**
Added to Server instead of RemoteServer so we have the same public
interface in both Local and Remote servers.
The method returns false when using the local Fusion driver.

### CODE REVIEW

**Comment by lstoll** [comment]
:+1:

**Comment by rubiojr** [comment]
:boom:

**Comment by rubiojr** [comment]
@lstoll I do not have privileges to merge I think.

**Comment by lstoll** [comment]
@rubiojr you should now!

**Comment by rubiojr** [comment]
@lstoll :heart:

**Pull request merged**
