### PR TITLE
Add :name to the LocalServer attributes.

### PR DESCRIPTION
**Pull request by calavera**
This makes both server implementations more consistent and allow to servers by name no matter what.

/cc @lstoll

### CODE REVIEW

**Comment by lstoll** [comment]
What are you using :name for on the remote instance? It's just a freeform textfield there, you can't actually load a server by it.

If you're just using it to provide a 'friendly' name for the server then sure, :ship: this - but in the near future I'll move :name on local to the same thing - something stored as machine metadata, rather than usable to find/retrieve the VM.

**Comment by calavera** [comment]
It's just because the toolchain explodes searching for vms because the local server doesn't have the method `name`.  

Sorry, I should have been more explicit.

**Comment by calavera** [comment]
This is what happens trying to look for local servers:

```
/Users/calavera/github/enterprise-toolchain/lib/enterprise/toolchain/conduits/server/find.rb:17:in `block in filter': undefined method `name' for #<Fog::Compute::Octocloud::LocalServer:0x007fd57fd7a5a8> (NoMethodError)
    from /Users/calavera/github/enterprise-toolchain/vendor/bundle/ruby/1.9.1/bundler/gems/fog-2ab2111a2ede/lib/fog/core/collection.rb:24:in `each'
    from /Users/calavera/github/enterprise-toolchain/vendor/bundle/ruby/1.9.1/bundler/gems/fog-2ab2111a2ede/lib/fog/core/collection.rb:24:in `each'
    from /Users/calavera/github/enterprise-toolchain/lib/enterprise/toolchain/helpers/compute.rb:10:in `find_all'
    from /Users/calavera/github/enterprise-toolchain/lib/enterprise/toolchain/helpers/compute.rb:10:in `find'
    from /Users/calavera/github/enterprise-toolchain/lib/enterprise/toolchain/conduits/find.rb:28:in `run'
    from /Users/calavera/github/enterprise-toolchain/lib/enterprise/toolchain/conduits/server/find.rb:23:in `run'
```

**Comment by lstoll** [comment]
Right, looks like when @benburkert rewrote toolchain he started fetching all machines and filtering by name, rather than fetching by the ID. Looks like this one done to make it easier to use a 'name' with EC2 as well.

I'm merging this now, this works in this case, but I'm going to revisit this in the near future - I'd rather replace the name field with a tagging implementation as well.

**Pull request merged**
