### PR TITLE
Add request to import VMDKs as cubes (Fusion/WS)

### PR DESCRIPTION
**Pull request by rubiojr**
The VMX generation code is way too simple, but I can move
forward with this without having to write a proper VMX reading/writing
library.

Added example and some tests.

### CODE REVIEW

**Comment by rubiojr** [comment]
Refs #22

**Comment by rubiojr** [comment]
@lstoll I've got this happily working with local Workstation. Need some :eyes:

**Comment by lstoll** [comment]
nice, :shipit:

**Comment by rubiojr** [comment]
Fixes #22

**Pull request merged**
